#ifndef REPORTS_H
#define REPORTS_H

#define NAMEVAL(name) #name " = " xstr(name)
#define xstr(a) str(a)
#define str(a) #a
/** Macros extraídas de contiki/core/contiki-default-conf.h
CONTIKI_DEFAULT_CONF_H
NETSTACK_CONF_RADIO
NETSTACK_CONF_FRAMER
NETSTACK_CONF_RDC
NETSTACK_CONF_MAC
NETSTACK_CONF_LLSEC
LLSEC802154_CONF_SECURITY_LEVEL
NETSTACK_CONF_NETWORK
NETSTACK_CONF_RDC_CHANNEL_CHECK_RATE
QUEUEBUF_CONF_NUM
NETSTACK_CONF_WITH_IPV6
UIP_CONF_BUFFER_SIZE
UIP_CONF_ROUTER
UIP_CONF_IPV6_RPL
UIP_CONF_MAX_ROUTES
UIP_CONF_UDP
UIP_CONF_MAX_CONNECTIONS
UIP_CONF_TCP
UIP_CONF_MAX_CONNECTIONS
UIP_CONF_TCP_SPLIT
NBR_TABLE_CONF_MAX_NEIGHBORS
UIP_CONF_ND6_SEND_NA
SICSLOWPAN_CONF_MAX_MAC_TRANSMISSIONS
SICSLOWPAN_CONF_FRAG
SICSLOWPAN_CONF_MAC_MAX_PAYLOAD
SICSLOWPAN_CONF_COMPRESSION_THRESHOLD
SICSLOWPAN_CONF_COMPRESSION
CONTIKIMAC_CONF_WITH_PHASE_OPTIMIZATION
*/
/*
 * grep '^#define' core/contiki-default-conf.h | cut -d' ' -f2 | sed -r 's/(.+)/printf(NAMEVAL(\1) "\\n");\\\\/g'
 */

#define REPORT() do{\
    printf("Si una macro no está definida su valor es igual a su nombre\n");\
    printf(NAMEVAL(NETSTACK_CONF_RADIO) "\n");\
    printf(NAMEVAL(NETSTACK_CONF_FRAMER) "\n");\
    printf(NAMEVAL(NETSTACK_CONF_RDC) "\n");\
    printf(NAMEVAL(NETSTACK_CONF_MAC) "\n");\
    printf(NAMEVAL(NETSTACK_CONF_LLSEC) "\n");\
    printf(NAMEVAL(LLSEC802154_CONF_SECURITY_LEVEL) "\n");\
    printf(NAMEVAL(NETSTACK_CONF_NETWORK) "\n");\
    printf(NAMEVAL(NETSTACK_CONF_RDC_CHANNEL_CHECK_RATE) "\n");\
    printf(NAMEVAL(QUEUEBUF_CONF_NUM) "\n");\
    printf(NAMEVAL(NETSTACK_CONF_WITH_IPV6) "\n");\
    printf(NAMEVAL(UIP_CONF_BUFFER_SIZE) "\n");\
    printf(NAMEVAL(UIP_CONF_ROUTER) "\n");\
    printf(NAMEVAL(UIP_CONF_IPV6_RPL) "\n");\
    printf(NAMEVAL(UIP_CONF_MAX_ROUTES) "\n");\
    printf(NAMEVAL(UIP_CONF_UDP) "\n");\
    printf(NAMEVAL(UIP_CONF_MAX_CONNECTIONS) "\n");\
    printf(NAMEVAL(UIP_CONF_TCP) "\n");\
    printf(NAMEVAL(UIP_CONF_MAX_CONNECTIONS) "\n");\
    printf(NAMEVAL(UIP_CONF_TCP_SPLIT) "\n");\
    printf(NAMEVAL(NBR_TABLE_CONF_MAX_NEIGHBORS) "\n");\
    printf(NAMEVAL(UIP_CONF_ND6_SEND_NA) "\n");\
    printf(NAMEVAL(SICSLOWPAN_CONF_MAX_MAC_TRANSMISSIONS) "\n");\
    printf(NAMEVAL(SICSLOWPAN_CONF_FRAG) "\n");\
    printf(NAMEVAL(SICSLOWPAN_CONF_MAC_MAX_PAYLOAD) "\n");\
    printf(NAMEVAL(SICSLOWPAN_CONF_COMPRESSION_THRESHOLD) "\n");\
    printf(NAMEVAL(SICSLOWPAN_CONF_COMPRESSION) "\n");\
    printf(NAMEVAL(CONTIKIMAC_CONF_WITH_PHASE_OPTIMIZATION) "\n");\
}while(0)

#endif
